chat-con/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('chat.urls')),
    url(r'', include('social_django.urls', namespace='social')),
]

chat/urls.py
from django.conf.urls import url
from . import views

app_name = 'chat'

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^login/$', views.login_form, name='login'),
    url(r'^signup/$', views.signup_form, name='signup'),
    url(r'^logout/$', views.log_out, name='logout'),
    url(r'^contact_us/$', views.contact_form, name='contact'),
    url(r'^auth_complete/$', views.social_auth, name='socauth'),
]

chat/models.py
from django.db import models


class User(models.Model):
    firstname = models.CharField(max_length=50, default='none')
    lastname = models.CharField(max_length=70, default=' ')

    username = models.CharField(max_length=32, primary_key=True)
    email = models.EmailField(max_length=50, unique=True)

    password = models.CharField(max_length=100)
    is_online = models.BooleanField(default=False)
    
    objects = models.Manager()

    def __str__(self):
        return self.username

chat/forms.py
from django import forms


class SignUpForm(forms.Form):
    fname = forms.CharField(max_length=50)
    lname = forms.CharField(max_length=50)
    passwd = forms.CharField(max_length=32, widget=forms.PasswordInput)

    username = forms.CharField(max_length=80)
    phn_num = forms.CharField(max_length=13)

    source = forms.CharField(max_length=50, widget=forms.HiddenInput())

    def clean(self):
        cleaned_data = super(SignUpForm, self).clean()

        fname = cleaned_data.get('fname')
        lname = cleaned_data.get('lname')
        passwd = cleaned_data.get('passwd')

        username = cleaned_data.get('username')
        phn_num = cleaned_data.get('phn_num')

        if not username:
            raise forms.ValidationError("You've to enter a username.")
        elif not passwd:
            raise forms.ValidationError("You've to enter a valid password.")
        elif not phn_num:
            raise forms.ValidationError("Enter a valid phone number to verify the account.")


class ContactForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)
    message = forms.CharField(
        max_length=2000,
        widget=forms.Textarea(),
        help_text='Write here your message!'
    )
    source = forms.CharField(       # A hidden input for internal use
        max_length=50,              # tell from which page the user sent the message
        widget=forms.HiddenInput()
    )

    def clean(self):
        cleaned_data = super(ContactForm, self).clean()
        name = cleaned_data.get('name')
        email = cleaned_data.get('email')
        message = cleaned_data.get('message')
        if not name and not email and not message:
            raise forms.ValidationError('You have to write something!')

chat/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError

from .forms import ContactForm
from . import models

import json
import re
# import logging

# logging.basicConfig(filename='/home/mohit/Documents/git_repos/chat-con/debug.log',
#                     level=logging.DEBUG,
#                     filemode='w')
# logger = logging.getLogger()
# logger.debug('#logging starts!')
sentinel = 1  # is it login or signup request?


def save_info(unm, pwd, eml, fname, lname):
    user = models.User()
    user.firstname = fname
    user.lastname = lname
    user.username = unm
    user.password = pwd
    user.email = eml
    user.is_online = True
    user.save()


def login_auth(*args):
    try:
        user = models.User.objects.get(pk=args[0])
        pas = models.User.objects.filter(pk=args[0], password=args[1])
        if pas:
            user.is_online = True
            user.save()
            return 1
        else: return 0
    except ObjectDoesNotExist:
        return 0


def registration(**kwargs):
    unm = kwargs.get('uname', 0)
    pwd = kwargs.get('passwd', 0)
    eml = kwargs.get('email', 0)

    if unm and pwd and eml:
        try:
            models.User.objects.get(pk=unm)
            yield from (0, {'error': "Username already taken!"})
            return
        except ObjectDoesNotExist:
            pass

        if not re.match(r'', eml):
            yield from (0, {'error': "Enter a valid email address"})
            return

        try:
            save_info(unm, pwd, eml, kwargs.get('fname', ''), kwargs.get('lname', ''))
        except IntegrityError:
            yield from(0, {'error': "Email address already exist!"})
            return
        yield from(1, 0)

    else:
        yield from (0, 0)


def dashboard(request):
    _users_ = models.User.objects.filter(is_online__exact=True)
    online_users = []

    for usr in _users_:
        online_users.append(usr.username + ' - (' + usr.firstname + ' ' + usr.lastname + ')')

    try:
        uname = models.User.objects.get(username__exact=request.session.get('username'), password__exact=request.session.get('usr_pass', 0))
        uname.is_online = True
        uname.save()
        return render(request, 'chat/index.html', {
            'user_session': uname,
            'full_name': uname.firstname + ' ' + uname.lastname,
            'online': online_users,
            })
    except ObjectDoesNotExist:
        pass

    if request.method == 'POST':
        uname = request.POST['uname']
        passwd = request.POST['passwd']
        email = request.POST.get('email', 0)
        error = ''

        if sentinel:
            #  sign up in progress
            fname = request.POST.get('fname', 0)
            lname = request.POST.get('lname', 0)
            auth, error = registration(fname=fname, lname=lname, uname=uname, passwd=passwd, email=email)
        else:
            # login in progress
            auth = login_auth(uname, passwd)

        if auth:
            # start session
            request.session['username'] = uname
            request.session['usr_pass'] = passwd
            request.session['session_up'] = True
            U = models.User.objects.get(pk=uname)
            return render(request, 'chat/index.html', {
                'user_session': uname,
                'full_name': U.firstname + ' ' + U.lastname,
                'online': online_users,
            })

        else:
            # resend form
            if not sentinel:
                error = {'error': 'Wrong username or password!'}
                return render(request, 'chat/login.html', error)
            else:
                if not error:
                    error = {'error': 'Fields with (*) are mandatory!'}
                return render(request, 'chat/signup.html', error)
    return render(request, 'chat/index.html')


def login_form(request):
    if request.session.get('session_up', 0):
        url = reverse('chat:dashboard')
        return HttpResponseRedirect(url)
    global sentinel
    sentinel = 0
    return render(request, 'chat/login.html')


def signup_form(request):
    if request.session.get('session_up', 0):
        url = reverse('chat:dashboard')
        return HttpResponseRedirect(url)
    global sentinel
    sentinel = 1
    return render(request, 'chat/signup.html')


def log_out(request):
    try:
        u = models.User.objects.get(username__exact=request.session['username'])
        u.is_online = False
        u.save()
        del request.session['username']
        del request.session['usr_pass']
        request.session['session_up'] = False
    except:
        pass
    return redirect('https://chatcon.herokuapp.com/')


def contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            pass  # does nothing, just trigger the validation
    else:
        form = ContactForm()
    return render(request, 'chat/contact.html', {'form': form, 'user_session': request.session.get('username', '')})


def social_auth(request):
    auth_email = request.user.email
    auth_user = auth_email.split('@')[0]
    auth_fname = request.user.first_name
    auth_lname = request.user.last_name
    auth_full = auth_fname + ' ' + auth_lname
    auth_hash_pass = request.user.password
    
    try:
        models.User.objects.get(pk=auth_user)
    except ObjectDoesNotExist:
        save_info(auth_user, auth_hash_pass, auth_email, auth_fname, auth_lname)

    _users_ = models.User.objects.filter(is_online__exact=True)
    online_users = []

    for usr in _users_:
        online_users.append(usr.username + ' - (' + usr.firstname + ' ' + usr.lastname + ')')

    request.session['username'] = auth_user
    request.session['usr_pass'] = auth_hash_pass
    request.session['session_up'] = True

    user_data = {'user_session': auth_user,
        'full_name': auth_full,
        'online': online_users,
    }
    return render(request, 'chat/auth.html', user_data)

chat/templates/chat/auth.html
{% extends 'chat/base.html' %}

{% block div %}
	<a style="display:none;" id="to_dashboard" href="{% url 'chat:dashboard' %}"></a>
{% endblock %}

{% block script %}
<script>
	$(document).ready(function() {
		document.querySelector('#to_dashboard').click();
	});
</script>
{% endblock %}

chat/templates/chat/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=New+Rocker" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <title>Chat-con | Dashboard</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'chat/css/base.css' %}">
    {% block link %}
    {% endblock %}
    <link rel="shortcut icon" href="https://chatcon.herokuapp.com/static/chat/images/logo.png">
</head>
<body>
    <nav class="navbar navbar-expand-md fixed-top navbar-dark" role="navigation">
        <div class="container">
            <div class="col-md-2">
                <a class="navbar-brand" href="{% url 'chat:dashboard' %}"older;"   >Chat-con</a>
                <button class="pull-right navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar1">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbar1">
                <div class="col-md-7 offset-lg-1">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'chat:dashboard' %}">Home</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'chat:contact' %}">Contact Us</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="#">About Us</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="https://github.com/m0hitnegi/chat-con/issues" target="_blank">Report Issues</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-3 offset-lg-1">
                    <ul class="navbar-nav">
                    {% if user_session %}
                        <li class="nav-item active offset-md-5">
                            <a href="{% url 'chat:logout' %}" class="nav-link">Log out</a>
                        </li>
                    {% else %}
                        <li class="nav-item active">
                            <a href="{% url 'chat:login' %}" class="nav-link">Login</a>
                        </li>
                        <li class="nav-item active">
                            <a href="{% url 'chat:signup' %}" class="nav-link">Signup</a>
                        </li>
                    {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    {% block div %}
    {% endblock %}
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
{% block script %}
{% endblock %}
</html>

chat/templates/chat/contact.html
{% extends 'chat/base.html' %}

{% block div %}
	<div class="container" style="padding-top: 60px;">
		<form method="post" novalidate>
		  {% csrf_token %}
		  {{ form }}
		  <button type="submit">Submit</button>
		</form>
	</div>
{% endblock %}

chat/templates/chat/index.html
{% extends 'chat/base.html' %}

{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'chat/css/index.css' %}">
{% endblock %}

{% block div %}
	<div class="parallax">
		<p>
            {% if user_session %}
                <span class="round-corn" id="howdy-user">Welcome {{full_name}}!</span>
            {% else %}
                <a class="btn" href="{% url 'chat:signup' %}">Getting started</a>
            {% endif %}
		</p>
    </div>
    {% if user_session %}
        <div class="text-center">
            <i class="fa fa-chevron-circle-down" id="down-button">
                <a role="button"></a>
            </i>
        </div>
        <div class="container-fluid cont-fl-custom-bg">
            <div class="row" style="height: 36em;">
                <div class="col-md-3" style="overflow-y: auto; padding-top: 20px;">
                    <!-- <form action="" class="form-inline text-center">
                        <input type="text" class="form-control col-md-8" id="search-box" placeholder="Search a username" style="border-radius: 4px 0 0 4px;">
                        <button class="form-btn" type="submit"><strong>Search</strong></button>
                    </form> -->
                    <ul class="list-group text-center">
                        <li class="list-group-item list-group-item-success"><strong>Online</strong></li>
                    </ul>
                    <ul class="list-group text-center" id="online_users" style="overflow: auto;">
                        {% for usr in online %}
                            <li class="list-group-item list-group-item-primary"><button type="button" role="button" class="clickable-on round-corn" onclick="start_conv(this)">{{ usr }}</li>
                        {% endfor %}
                    </ul>
                </div>
               
                <div class="col-md-7 msg-box-border">
                    <div  id="user-selected" style="display:none;">
                        <div class="contact-navbar text-center round-corn">
                            <h4 id="current_name"></h4>
                        </div>
                        <div class="container">
                            <div style="height: 30em;">
                                <span id="add_new_area"></span>
                                <input type="text" class="round-corn" id="msg-input" placeholder="Enter your message here!" autocomplete="off">
                                <input type="button" name="now-message" class="form-btn" id="subm-btn" value="Send"/>
                            </div>
                        </div>
                    </div>
                    <div id="no-user-selection">
                    </div>
                </div>
                <div class="col-md-2" style="margin-top: 20px;">
                    <ul class="list-group text-center" id="new-msgs">
                        <!-- <li class="list-group-item blur-bg round-corn">
                            <a href="#" class="acnt-changes">Change your firstname</a>
                        </li>
                        <li class="list-group-item blur-bg round-corn">
                            <a href="#" class="acnt-changes">Change your lastname</a>
                        </li>
                        <li class="list-group-item blur-bg round-corn">
                            <a href="#" class="acnt-changes">Change your username</a>
                        </li>
                        <li class="list-group-item blur-bg round-corn">
                            <a href="#" class="acnt-changes">Change your phone number</a>
                        </li>
                        <li class="list-group-item blur-bg round-corn">
                            <a href="#" class="acnt-changes">Change your password</a>
                        </li> -->
                        <li class="list-group-item list-group-item-success" id="show-new" style="display: none;"><strong>New Message(s)</strong></li>
                        <li class="list-group-item list-group-item-warning" id="no-new">No new message! :(</li>
                    </ul>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block script %}
<script>
    var user = "{{ user_session }}";
    var fullname = "{{ full_name }}";
    if (user) {
        document.cookie = "username=" + user;
        document.cookie = "fullname=" + fullname;
    }
</script>
<script src="{% static 'chat/js/basic.js' %}"></script>
<script type="text/javascript" src='{% static "chat/js/reconnecting-websocket.min.js" %}'></script>
<script type="text/javascript" src="{% static 'chat/js/main.js' %}"></script>
{% endblock %}

chat/templates/chat/login.html
{% extends 'chat/base.html' %}

{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'chat/css/form.css' %}">
{% endblock %}

{% block div %}
    <div class="container text-center form-div">
        <center>
            <div class="col form-box">
                <h1>Log In</h1><hr>
                <form action="{% url 'chat:dashboard' %}" method="post" novalidate autocomplete="off">
                    {% csrf_token %}
                    <label for="username">
                        <strong>Username: </strong>
                        <input class="input-field" type="text" name="uname" id="username" placeholder="Enter your username" autofocus/>
                    </label>
                    <br>

                    <label for="password">
                        <strong>Password: </strong>
                        <input class="input-field" type="password" name="passwd" id="password" placeholder="********">
                    </label>
                    <br>
                    <button type="submit" class="btn btn-success" style="margin-bottom:5px;">Login</button><br>
                </form>
                <div>
                    <p>Or login with :<br>
                        <!-- <a href="{% url 'social:begin' 'github' %}">Github</a> -->
                        <a href="{% url 'social:begin' 'google-oauth2' %}">Google</a>
                        <!-- <fb:login-button scope="public_profile,email" onlogin="checkLoginState();">Facebook</fb:login-button> -->
                    </p>
                {% if error %}
                    <p style="margin-bottom:0;color:#ff0000;">{{ error }}</p>
                {% endif %}
                <hr>
                <a href="{% url 'chat:signup' %}">Create a new account</a> | <a href="#">Forgot Password?</a>
            </div>
        </center>
    </div>
{% endblock %}

{% block script %}
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '175150596679745',
      cookie     : true,
      xfbml      : true,
      version    : 'v3.0'
    });
      
    FB.AppEvents.logPageView();   
      
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

function checkLoginState() {
  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });
}
</script>
{% endblock %}

chat/templates/chat/signup.html
{% extends 'chat/base.html' %}

{% load static %}
{% block link %}
	<link rel="stylesheet" type="text/css" href="{% static 'chat/css/form.css' %}">
{% endblock %}

{% block div %}
    <div class="container text-center form-div">
    	<center>
    		<div class="col form-box">
    			<h1>Sign Up</h1><hr>
		        <form action="{% url 'chat:dashboard' %}" method="post" class="signup-auth" autocomplete="off" novalidate autocomplete="off">
                    {% csrf_token %}
                    <label for="fname">First Name: </label>
                    <input type="text" id="fname" name="fname" class="input-field" placeholder="Enter your first name." autofocus>

                    <label for="lname">Last Name:</label>
                    <input type="text" id="lname" name="lname" class="input-field" placeholder="Enter your last name.">

                    <label for="uname">Username:*</label>
                    <input type="text" id="uname" name="uname" class="input-field" placeholder="Enter a unique username.">
                    <p class="in-valid offset-2" style="color:#ff0000;margin-left:15%;" id="no-spc">No whitespaces allowed!</p>

                    <label for="passwd">Password:*</label>
                    <input type="password" id="passwd" name="passwd" class="input-field" placeholder="Enter a strong password."/>
                    <p class="in-valid" style="color:#ff0000;" id="weak-pass">Strength: Weak!</p>
                    <p class="in-valid" style="color:#ff9800;" id="med-pass">Strength: Medium!</p>
                    <p class="in-valid" style="color:#4caf50;" id="str-pass">Strength: Strong!</p>

                    <label for="eml" class="offset-1">Email:*</label>
                    <input type="text" id="eml" name="eml" class="input-field" placeholder="Enter your email address."/>
                    <p class="in-valid" style="color:#ff0000;" id="inv-eml">Invalid!</p>
                    <p class="in-valid" style="color:#4caf50;" id="val-eml">Valid!</p>

                    <button type="submit" class="btn btn-success">Sign Up</button><br>
    		    </form>
                {% if error %}
                    <p style="color:#0000ff;margin:0">{{ error }}</p>
                {% endif %}
                <a href="{% url 'chat:login' %}">Already have an account?</a>
   	    	</div>
    	</center>
    </div>
{% endblock %}

{% block script %}
<script src="{% static 'chat/js/form.js' %}"></script>
{% endblock %}